### ISSUE TITLE
Checksums for release artefacts

### ISSUE THREAD

**Issue by franchb** [snyball/tombl#1]
Such a handy tool!

I think many people who want to use such a tool for DevOps automation daily routines need checksums of release artefacts.

Random example is https://github.com/zhboner/realm/releases/tag/v2.4.5

Thank you!

**Comment by snyball** [comment]
@franchb That sounds like a really good idea! I noticed that in the repo you linked, the `sha256sum`s are made from the tarball, and not the executable itself. Is that conventional?

**Comment by snyball** [comment]
Should be resolved by https://github.com/snyball/tombl/releases/tag/v0.2.3, unless there's a preference for having the hashsum be of the binary.

**Comment by franchb** [comment]
I think calculating checksum from the tarball is enough unless someone needs checksum for the executable itself.

Thank you!
